## Create QE score using an LLM-based approach

In [1]:
#%pip install openai python-dotenv
import pandas as pd
from dotenv import load_dotenv
import os
from openai import OpenAI

#%pip install git+https://github.com/MicrosoftTranslator/GEMBA.git
from gemba.gemba_mqm_utils import (
    TEMPLATE_GEMBA_MQM,
    apply_template,
    parse_mqm_answer
)

In [2]:
data_path = '/Users/tuedungtruong/Documents/PythonProjects/msc-thesis/data/dataset_qe/divemt_cometkiwi_qescore.tsv'
df = pd.read_csv(data_path, sep ='\t')
#print(df.shape)
#print(df.columns)

In [3]:
#Create dictionary of language code mapped to its language name
languages = {
    'tur':'Turkish',
    'ita':'Italian',
    'ukr':'Ukranian',
    'nld':'Dutch',
    'vie':'Vietnamese',
    'ara':'Arabic'
}

In [4]:
load_dotenv()
api_key = os.getenv('OPENROUTER_API_KEY')
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

open_model = "google/gemma-3-27b-it"
proprietary_model = "openai/gpt-4.1-mini"

In [5]:
print (api_key is not None)

True

In [6]:
gemba_input_df = df.copy()
#add source language feature to df, value for all cells is English
gemba_input_df['source_lang'] = "English"
#add target language feature to df, value is taken from the languages dictionary
gemba_input_df['target_lang'] = gemba_input_df['lang_id'].map(languages)

print(gemba_input_df['source_lang'].shape)
print (gemba_input_df['source_lang'].unique())
print (gemba_input_df['source_lang'].nunique())
print(gemba_input_df.shape)
gemba_input_df.head(5)

(5160,)
['English']
1
(5160, 67)

,unit_id,flores_id,item_id,subject_id,task_type,translation_type,src_len_chr,mt_len_chr,tgt_len_chr,src_len_wrd,...,src_annotations,mt_tokens,mt_annotations,tgt_tokens,tgt_annotations,src_wmt22_qe,mt_wmt22_qe,qe_cometkiwi,source_lang,target_lang
0,flores101-main-tur-100-pe1-1,894,flores101-main-1001,tur_t1,pe1,pe,124,126.0,128,21,...,"[{'lemma': 're-entry', 'upos': 'NOUN', 'feats'...","['Yeniden', 'giriş', 'şoku', 'kültür', 'şokund...","[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['Yeniden', 'giriş', 'şoku', ',', 'kültür', 'ş...","[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'OK', 'O...",0.863117,English,Turkish
1,flores101-main-tur-100-pe1-2,895,flores101-main-1002,tur_t1,pe1,pe,137,117.0,117,22,...,"[{'lemma': 'traveller', 'upos': 'NOUN', 'feats...","['Yeni', 'kültüre', 'kolayca', 'uyum', 'sağlay...","[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['Yeni', 'kültüre', 'kolayca', 'uyum', 'sağlay...","[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...",0.868266,English,Turkish
2,flores101-main-tur-100-pe1-3,896,flores101-main-1003,tur_t1,pe1,pe,127,133.0,148,22,...,"[{'lemma': 'when', 'upos': 'SCONJ', 'feats': '...","['Yurtdışında', 'yaşadıktan', 'sonra', 'eve', ...","[{'lemma': 'yurtdışı', 'upos': 'NOUN', 'feats'...","['Yurtdışında', 'yaşadıktan', 'sonra', 'ülkeni...","[{'lemma': 'yurtdışı', 'upos': 'NOUN', 'feats'...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'BAD', 'B...","['OK', 'OK', 'OK', 'BAD', 'OK', 'BAD', 'OK', '...",0.891622,English,Turkish
3,flores101-main-tur-100-pe1-4,897,flores101-main-1004,tur_t1,pe1,pe,134,145.0,166,22,...,"[{'lemma': 'when', 'upos': 'SCONJ', 'feats': '...","['İlk', 'başta', 'yurt', 'dışına', 'çıktığınız...","[{'lemma': 'ilk', 'upos': 'ADJ', 'feats': '', ...","['Yurt', 'dışına', 'ilk', 'çıktığınızda', 'çev...","[{'lemma': 'yurt', 'upos': 'NOUN', 'feats': 'C...","['OK', 'OK', 'OK', 'BAD', 'OK', 'BAD', 'BAD', ...","['BAD', 'BAD', 'BAD', 'OK', 'BAD', 'BAD', 'OK'...",0.865835,English,Turkish
4,flores101-main-tur-100-pe1-5,898,flores101-main-1005,tur_t1,pe1,pe,107,89.0,94,15,...,"[{'lemma': 'person', 'upos': 'NOUN', 'feats': ...","['İnsanlar', 'bu', 'sabır', 'tahmin', 'edemeye...","[{'lemma': 'insan', 'upos': 'NOUN', 'feats': '...","['İnsanlar', ',', 'ülkesine', 'dönenlere', 'de...","[{'lemma': 'insan', 'upos': 'NOUN', 'feats': '...","['OK', 'BAD', 'OK', 'BAD', 'BAD', 'BAD', 'OK',...","['OK', 'BAD', 'BAD', 'BAD', 'BAD', 'OK', 'OK',...",0.635008,English,Turkish

In [7]:
#Prepare inputs for GEMBA

gemba_inputs = []

for _, row in gemba_input_df.iterrows():
    segment_data ={
        "source_lang": row["source_lang"],
        "target_lang": row["target_lang"],
        "source_seg": row["src_text"],
        "target_seg": row["mt_text"]
        }
    
    input_item = {
        "unit_id": row["unit_id"],
        "segment_data": segment_data
    }
    gemba_inputs.append(input_item)

In [10]:
# Create qe score with open model google/gemma-3-27b-it

gemma_results=[] #list to store results from Gemma

for i, item in enumerate (gemba_inputs, start =1):

    messages = apply_template(
        TEMPLATE_GEMBA_MQM,
        item['segment_data']
    )

    try:
        response = client.chat.completions.create(
            model = open_model,
            messages = messages,
            temperature = 0
        )
        raw_output = response.choices[0].message.content
        
        score = parse_mqm_answer (raw_output)
        
        errors = parse_mqm_answer(
            raw_output,
            list_mqm_errors = True
        )
        gemma_results.append(
            {
                'unit_id': item['unit_id'],
                'qe_gemba_gemma3': score,
                'gemba_gemma3_errors': dict(errors),
                'gemba_gemma_raw_output': raw_output
            }
        )

    except Exception as e:
        gemma_results.append(
            {
                'unit_id': item['unit_id'],
                'qe_gemba_gemma3': None,
                'gemba_gemma3_errors': None,
                'gemba_gemma3_raw_output': None  
            }
        )
        print (f'Error at row {i}:{e}')

    if i % 100 == 0:
        checkpoint_df = pd.DataFrame (gemma_results)
        checkpoint_df.to_csv("../data/dataset_qe/gemba_gemma3_qe_outputs.tsv", sep ='\t', index = False)

the primary issue is the character encoding. the use of "q" instead of "k" in "qaranlıq" makes the word incorrect and difficult to understand for a turkish speaker. this is a *critical* error because it directly impacts readability and meaning. the rest of the translation appears grammatically correct and conveys the original meaning, though it might not be the most elegant turkish phrasing.
the primary issue is the character encoding. the use of "q" instead of "k" in "qaranlıq" makes the word incorrect and difficult to understand for a turkish speaker. this is a *critical* error because it directly impacts readability and meaning. the rest of the translation appears grammatically correct and conveys the original meaning, though it might not be the most elegant turkish phrasing.
the primary issue is the character encoding. "müxtəlifliği" appears to be azerbaijani or another similar language, not turkish. this renders the word unrecognizable and significantly impacts comprehension. while the rest of the translation *appears* structurally correct, the core vocabulary error makes it a critical issue.
the primary issue is the character encoding. "müxtəlifliği" appears to be azerbaijani or another similar language, not turkish. this renders the word unrecognizable and significantly impacts comprehension. while the rest of the translation *appears* structurally correct, the core vocabulary error makes it a critical issue.
spelling - "balasubramanyan" (should be "balasubramanian") - this is a minor spelling error as the name is still recognizable.
spelling - "balasubramanyan" (should be "balasubramanian") - this is a minor spelling error as the name is still recognizable.
the key error is the mistranslation of "endangered." the turkish phrase "nesli tükendi" *only* means "became extinct." using it for both "extinct" and "endangered" loses a crucial distinction in the original meaning. this is a critical error because it changes the information conveyed. while understandable, the nuance is lost.
the key error is the mistranslation of "endangered." the turkish phrase "nesli tükendi" *only* means "became extinct." using it for both "extinct" and "endangered" loses a crucial distinction in the original meaning. this is a critical error because it changes the information conveyed. while understandable, the nuance is lost.
overall, this is a very good translation. the minor issue is a slight awkwardness in the phrasing, but it doesn't impede understanding.
overall, this is a very good translation. the minor issue is a slight awkwardness in the phrasing, but it doesn't impede understanding.
the repeated "suy" is a significant mistranslation, completely changing the meaning. it renders the sentence incomprehensible without context. the rest of the sentence structure is passable, even if not perfectly natural-sounding, making it a critical error rather than a major one.
the repeated "suy" is a significant mistranslation, completely changing the meaning. it renders the sentence incomprehensible without context. the rest of the sentence structure is passable, even if not perfectly natural-sounding, making it a critical error rather than a major one.
the core error is the mistranslation of "cherry blossom viewing" (hanami) as "afforestation" (ağaçlandırma). this fundamentally changes the meaning of the sentence. while the rest of the sentence is grammatically correct and flows well in turkish, the central concept is incorrect, making it a critical error.
the core error is the mistranslation of "cherry blossom viewing" (hanami) as "afforestation" (ağaçlandırma). this fundamentally changes the meaning of the sentence. while the rest of the sentence is grammatically correct and flows well in turkish, the central concept is incorrect, making it a critical error.
the core error is the complete mistranslation of "plum blossoms" as "grass trees." this fundamentally changes the meaning of the sentence and is therefore a critical error. the rest of the sentence structure is reasonably accurate, even if not perfectly elegant.
the core error is the complete mistranslation of "plum blossoms" as "grass trees." this fundamentally changes the meaning of the sentence and is therefore a critical error. the rest of the sentence structure is reasonably accurate, even if not perfectly elegant.
the core issue is the mistranslation of "ran back." "kaçtılar" means "they ran away" or "they fled," which completely changes the meaning of the sentence. the original implies they returned to the scene, while the translation implies they escaped it. this is a critical error because it fundamentally alters the narrative.
the core issue is the mistranslation of "ran back." "kaçtılar" means "they ran away" or "they fled," which completely changes the meaning of the sentence. the original implies they returned to the scene, while the translation implies they escaped it. this is a critical error because it fundamentally alters the narrative.
the core issue is the translation of "caliber." if "kaileber" is a direct transliteration attempt of a misspelled word, it's a critical error because it renders the sentence nonsensical. it's likely the mt system struggled with the unusual spelling in the source and produced a similarly incorrect output. the rest of the sentence is grammatically correct and conveys the general idea, even if the specific detail is lost due to the "kaileber" error.
the core issue is the translation of "caliber." if "kaileber" is a direct transliteration attempt of a misspelled word, it's a critical error because it renders the sentence nonsensical. it's likely the mt system struggled with the unusual spelling in the source and produced a similarly incorrect output. the rest of the sentence is grammatically correct and conveys the general idea, even if the specific detail is lost due to the "kaileber" error.
the key error is the verb "kaçtı" which means "ran away" or "escaped." the original english sentence indicates movement *back* to the location, while the turkish translation implies fleeing the scene. this significantly alters the meaning and is therefore a critical error. while a native speaker might understand the general idea, the nuance is lost and could lead to misinterpretation.
the key error is the verb "kaçtı" which means "ran away" or "escaped." the original english sentence indicates movement *back* to the location, while the turkish translation implies fleeing the scene. this significantly alters the meaning and is therefore a critical error. while a native speaker might understand the general idea, the nuance is lost and could lead to misinterpretation.
the core meaning is altered by translating "intrusive" as "effective." the original sentence highlights the *invasive* nature of the searches, while the translation suggests they are simply *more effective*. this is a significant shift in meaning. while the rest of the translation is grammatically correct and understandable, the key descriptor is wrong, making it a critical error.
the core meaning is altered by translating "intrusive" as "effective." the original sentence highlights the *invasive* nature of the searches, while the translation suggests they are simply *more effective*. this is a significant shift in meaning. while the rest of the translation is grammatically correct and understandable, the key descriptor is wrong, making it a critical error.
the core error is the attribution of the action "migrating" to the pigs themselves. the original english sentence implies the *disease* is what moves from pigs to humans. translating it as "the pigs migrate" fundamentally changes the meaning and is a critical error. the rest of the translation is grammatically correct and conveys the general idea, even with the core error present.
the core error is the attribution of the action "migrating" to the pigs themselves. the original english sentence implies the *disease* is what moves from pigs to humans. translating it as "the pigs migrate" fundamentally changes the meaning and is a critical error. the rest of the translation is grammatically correct and conveys the general idea, even with the core error present.
the core issue is the translation of "badly tucked." translating it as "malata" (sick) completely changes the meaning and makes the sentence nonsensical in the context of a car race. it suggests the wheel *was ill*, rather than improperly attached. this is a critical error because it fundamentally misrepresents the reason for the race ending. the rest of the translation is reasonably accurate and fluent.
the core issue is the translation of "badly tucked." translating it as "malata" (sick) completely changes the meaning and makes the sentence nonsensical in the context of a car race. it suggests the wheel *was ill*, rather than improperly attached. this is a critical error because it fundamentally misrepresents the reason for the race ending. the rest of the translation is reasonably accurate and fluent.
overall: very good translation. the minor point is debatable and doesn't significantly impact understanding.
overall: very good translation. the minor point is debatable and doesn't significantly impact understanding.
the verb "risucchiato" is a significant error. "douse" means to extinguish a fire by pouring water on it. "risucchiato" implies *sucking* the fire up, which is nonsensical in this context. this fundamentally changes the meaning of the sentence and is therefore a critical error. the rest of the translation is grammatically correct and conveys the basic information, even if it's not the most elegant italian.
the verb "risucchiato" is a significant error. "douse" means to extinguish a fire by pouring water on it. "risucchiato" implies *sucking* the fire up, which is nonsensical in this context. this fundamentally changes the meaning of the sentence and is therefore a critical error. the rest of the translation is grammatically correct and conveys the basic information, even if it's not the most elegant italian.
overall: this is a very good translation. the minor punctuation point is a stylistic preference and doesn't impact understanding.
overall: this is a very good translation. the minor punctuation point is a stylistic preference and doesn't impact understanding.
the core error is the attribution of the migration action to the pigs themselves. the english sentence clearly states the *disease* is carried by pigs and then transmitted to humans. the italian translation incorrectly states the pigs migrate to humans. this fundamentally alters the meaning and is a critical error. while a native italian speaker might understand the intended meaning from context, the literal translation is incorrect and misleading.
the core error is the attribution of the migration action to the pigs themselves. the english sentence clearly states the *disease* is carried by pigs and then transmitted to humans. the italian translation incorrectly states the pigs migrate to humans. this fundamentally alters the meaning and is a critical error. while a native italian speaker might understand the intended meaning from context, the literal translation is incorrect and misleading.
overall: the translation is very good and largely error-free. the minor issue is a stylistic one and doesn't significantly impact comprehension.
overall: the translation is very good and largely error-free. the minor issue is a stylistic one and doesn't significantly impact comprehension.
the translation of "dam" as "baracco" is a significant error. "baracco" means "shack" or "hut," completely changing the meaning of the sentence. this is a critical error because it makes the sentence nonsensical in context. the rest of the translation is grammatically correct and conveys the intended meaning, albeit with a crucial factual error.
the translation of "dam" as "baracco" is a significant error. "baracco" means "shack" or "hut," completely changing the meaning of the sentence. this is a critical error because it makes the sentence nonsensical in context. the rest of the translation is grammatically correct and conveys the intended meaning, albeit with a crucial factual error.
while understandable, it's grammatically slightly off. it's a minor error as it doesn't significantly hinder comprehension.
while understandable, it's grammatically slightly off. it's a minor error as it doesn't significantly hinder comprehension.
spelling - "зв 'язку" (apostrophe placement - stylistic, but potentially a minor error depending on ukrainian orthographic rules)
spelling - "зв 'язку" (apostrophe placement - stylistic, but potentially a minor error depending on ukrainian orthographic rules)
**explanation:** the core error is the mistranslation of "current." using "stream" and "escape" fundamentally alters the meaning of the sentence, making it nonsensical in the context of swimming. this is a critical error because it destroys the intended message. the rest of the translation is grammatically correct and conveys the remaining idea reasonably well, even with the initial misunderstanding.
**explanation:** the core error is the mistranslation of "current." using "stream" and "escape" fundamentally alters the meaning of the sentence, making it nonsensical in the context of swimming. this is a critical error because it destroys the intended message. the rest of the translation is grammatically correct and conveys the remaining idea reasonably well, even with the initial misunderstanding.
the core error is the mistranslation of "tidal forces" as "thermal forces". this fundamentally changes the meaning of the sentence in a scientific context. tidal forces are a specific gravitational effect, while thermal forces relate to heat. this is a critical error because it misrepresents the scientific concept being discussed. the rest of the translation appears grammatically correct and conveys the general idea, even with the central scientific error.
the core error is the mistranslation of "tidal forces" as "thermal forces". this fundamentally changes the meaning of the sentence in a scientific context. tidal forces are a specific gravitational effect, while thermal forces relate to heat. this is a critical error because it misrepresents the scientific concept being discussed. the rest of the translation appears grammatically correct and conveys the general idea, even with the central scientific error.
the core error is the mistranslation of "correlation" as "difference." this fundamentally changes the meaning of the sentence, making it incorrect and difficult to understand in the intended context. this is a critical error because it alters the core message. the rest of the sentence is grammatically correct and flows reasonably well given the initial mistranslation.
the core error is the mistranslation of "correlation" as "difference." this fundamentally changes the meaning of the sentence, making it incorrect and difficult to understand in the intended context. this is a critical error because it alters the core message. the rest of the sentence is grammatically correct and flows reasonably well given the initial mistranslation.
the key error is the mistranslation of "damaged bodies." in the context of accidents and healthcare, it clearly refers to *people* who have been injured, not the vehicles themselves. translating it as "damaged car bodies" fundamentally changes the meaning of the sentence and is a critical error. the rest of the translation is reasonably accurate and fluent.
the key error is the mistranslation of "damaged bodies." in the context of accidents and healthcare, it clearly refers to *people* who have been injured, not the vehicles themselves. translating it as "damaged car bodies" fundamentally changes the meaning of the sentence and is a critical error. the rest of the translation is reasonably accurate and fluent.
the core meaning is lost due to the mistranslation of "premature labor." "працездатність" refers to work capacity or efficiency, which completely changes the sentence's meaning. this is a critical error as it makes the sentence nonsensical in the context of medical research. the rest of the translation is grammatically correct and conveys the basic structure of the original sentence, even if it lacks nuance.
the core meaning is lost due to the mistranslation of "premature labor." "працездатність" refers to work capacity or efficiency, which completely changes the sentence's meaning. this is a critical error as it makes the sentence nonsensical in the context of medical research. the rest of the translation is grammatically correct and conveys the basic structure of the original sentence, even if it lacks nuance.
the primary error is grammatical. the word "отруту" is in the wrong case. it needs to be in the accusative case to correctly follow the preposition "щодо" (regarding/concerning). this impacts comprehension, making it a critical error. the rest of the translation is understandable, though not perfectly polished.
the primary error is grammatical. the word "отруту" is in the wrong case. it needs to be in the accusative case to correctly follow the preposition "щодо" (regarding/concerning). this impacts comprehension, making it a critical error. the rest of the translation is understandable, though not perfectly polished.
the presence of the japanese character "関" within the ukrainian text is a critical error as it renders the sentence unreadable and disrupts comprehension. it's a clear character encoding issue. the rest of the translation appears to convey the meaning of the source sentence reasonably well, even if it's not perfectly elegant. therefore, no major or minor errors were identified.
the presence of the japanese character "関" within the ukrainian text is a critical error as it renders the sentence unreadable and disrupts comprehension. it's a clear character encoding issue. the rest of the translation appears to convey the meaning of the source sentence reasonably well, even if it's not perfectly elegant. therefore, no major or minor errors were identified.
the critical error significantly alters the meaning. the english states schneider *needed* reconstructive surgery, while the ukrainian implies he was *assigned* the task of reconstructing his face. this is a fundamental misunderstanding of the original sentence. the rest of the translation is reasonably accurate and fluent.
the critical error significantly alters the meaning. the english states schneider *needed* reconstructive surgery, while the ukrainian implies he was *assigned* the task of reconstructing his face. this is a fundamental misunderstanding of the original sentence. the rest of the translation is reasonably accurate and fluent.
**explanation:** the biggest issue is the handling of "cep". without knowing what cep stands for in the original context, a direct transliteration is unhelpful and essentially renders the sentence incomprehensible. this is a critical error because it prevents understanding of the core information. the rest of the translation appears grammatically correct and conveys the basic timeframe.
**explanation:** the biggest issue is the handling of "cep". without knowing what cep stands for in the original context, a direct transliteration is unhelpful and essentially renders the sentence incomprehensible. this is a critical error because it prevents understanding of the core information. the rest of the translation appears grammatically correct and conveys the basic timeframe.
the biggest issue is the use of "гонця". while technically a "rider", it implies a specific *type* of rider (one carrying a message) and is not the general term for someone riding a horse. this significantly alters the meaning and is therefore a critical error. the rest of the translation is grammatically correct and conveys the basic idea, even if it's not perfectly natural phrasing.

In [11]:
print(checkpoint_df.shape)
print(checkpoint_df.head())
print(checkpoint_df["qe_gemba_gemma3"].isna().sum())

(5100, 4)
                        unit_id  qe_gemba_gemma3  \
0  flores101-main-tur-100-pe1-1                0
1  flores101-main-tur-100-pe1-2                0
2  flores101-main-tur-100-pe1-3                0
3  flores101-main-tur-100-pe1-4               -1
4  flores101-main-tur-100-pe1-5              -25

                                 gemba_gemma3_errors  \
0                                                 {}
1                                                 {}
2                                                 {}
3  {'minor': ['fluency/grammar - the sentence str...
4  {'critical': ['accuracy/mistranslation - the s...

                              gemba_gemma_raw_output
0  \nCritical:\nno-error\nMajor:\nno-error\nMinor...
1  \nCritical:\nno-error\nMajor:\nno-error\nMinor...
2  \nCritical:\nno-error\nMajor:\nno-error\nMinor...
3  \nCritical:\nno-error\nMajor:\nno-error\nMinor...
4  \nCritical:\naccuracy/mistranslation - The sen...
0

In [17]:
gemma_results_df = pd.DataFrame(gemma_results)

"""
gemma_results_df.to_csv(
    "../data/dataset_qe/gemba_gemma3_qe_outputs.tsv",
    sep="\t",
    index=False
)
"""

print(gemma_results_df.shape)
print(gemma_results_df["qe_gemba_gemma3"].isna().sum())
gemma_results_df.head(10)

(5160, 4)
0

,unit_id,qe_gemba_gemma3,gemba_gemma3_errors,gemba_gemma_raw_output
0,flores101-main-tur-100-pe1-1,0,{},\nCritical:\nno-error\nMajor:\nno-error\nMinor...
1,flores101-main-tur-100-pe1-2,0,{},\nCritical:\nno-error\nMajor:\nno-error\nMinor...
2,flores101-main-tur-100-pe1-3,0,{},\nCritical:\nno-error\nMajor:\nno-error\nMinor...
3,flores101-main-tur-100-pe1-4,-1,{'minor': ['fluency/grammar - the sentence str...,\nCritical:\nno-error\nMajor:\nno-error\nMinor...
4,flores101-main-tur-100-pe1-5,-25,{'critical': ['accuracy/mistranslation - the s...,\nCritical:\naccuracy/mistranslation - The sen...
5,flores101-main-tur-101-pe2-1,-1,{'minor': ['fluency/punctuation - missing a fu...,\nCritical:\nno-error\nMajor:\nno-error\nMinor...
6,flores101-main-tur-101-pe2-2,0,{},\nCritical:\nno-error\nMajor:\nno-error\nMinor...
7,flores101-main-tur-101-pe2-3,-6,{'major': ['fluency/grammar - the sentence str...,\nCritical:\nno-error\n\nMajor:\nfluency/gramm...
8,flores101-main-tur-103-pe1-1,-1,"{'minor': ['style/awkward - ""ki"" (the use of ""...",\nCritical:\nno-error\nMajor:\nno-error\nMinor...
9,flores101-main-tur-103-pe1-2,-6,{'major': ['terminology/inappropriate for cont...,\nCritical:\nno-error\nMajor:\nterminology/ina...

In [18]:
# Create qe score with proprietary model openai/gpt-4.1-mini

gpt_results=[] #list to store results from Gpt4

for i, item in enumerate (gemba_inputs, start =1):

    messages = apply_template(
        TEMPLATE_GEMBA_MQM,
        item['segment_data']
    )

    try:
        response = client.chat.completions.create(
            model = proprietary_model,
            messages = messages,
            temperature = 0
        )
        raw_output = response.choices[0].message.content
        
        score = parse_mqm_answer (raw_output)
        
        errors = parse_mqm_answer(
            raw_output,
            list_mqm_errors = True
        )
        gpt_results.append(
            {
                'unit_id': item['unit_id'],
                'qe_gemba_gpt4_1_mini': score,
                'gemba_gpt4_1_mini_errors': dict(errors),
                'gemba_gpt4_1_mini_raw_output': raw_output
            }
        )

    except Exception as e:
        gpt_results.append(
            {
                'unit_id': item['unit_id'],
                'qe_gemba_gpt4_1_mini': None,
                'gemba_gpt4_1_mini_errors': None,
                'gemba_gpt4_1_mini_raw_output': None  
            }
        )
        print (f'Error at row {i}:{e}')

    if i % 100 == 0:
        checkpoint_df_gpt = pd.DataFrame (gpt_results)
        checkpoint_df_gpt.to_csv("../data/dataset_qe/gemba_gpt4_1_mini_qe_outputs.tsv", sep ='\t', index = False)

no minor errors identified.
no minor errors identified.
overall, no critical or major errors; minor issues only.
overall, no critical or major errors; minor issues only.
no major errors
no major errors
overall, the translation is accurate and fluent with only minor stylistic differences.
overall, the translation is accurate and fluent with only minor stylistic differences.
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
No error level for the translation accurately conveys the meaning of the source text, is fluent, and uses appropriate terminology and style.
No error level for the translation accurately conveys the meaning of the source text, is fluent, and uses appropriate terminology and style.
no critical or accuracy errors detected; meaning is preserved.
no critical or accuracy errors detected; meaning is preserved.
no major errors
no major errors
no other major errors
no other minor errors
no other major errors
no other minor errors
no critical errors.
no major errors.
no critical errors.
no major errors.
no major errors
no minor errors
no major errors
no minor errors
no other major errors
no other major errors
- critical: no critical errors that inhibit comprehension.
- major: mistranslation of "decertification" and partial omission of conditional nuance.
- minor: awkward phrasing and slight fluency issues.
- critical: no critical errors that inhibit comprehension.
- major: mistranslation of "decertification" and partial omission of conditional nuance.
- minor: awkward phrasing and slight fluency issues.
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no minor errors
no major errors
no minor errors
overall, no critical or major errors; minor fluency issue only.
overall, no critical or major errors; minor fluency issue only.
- fluency/punctuation: the turkish sentence is a bit long and could benefit from a comma after "carter'a dış politika konusunda danışmanlık yaptı" to improve readability, but this is minor and does not hinder comprehension.
- fluency/punctuation: the turkish sentence is a bit long and could benefit from a comma after "carter'a dış politika konusunda danışmanlık yaptı" to improve readability, but this is minor and does not hinder comprehension.
no major errors
no major errors
no major errors
summary: the phrase "magnetic reversals" is mistranslated as "kuyruksal geri dönüşlere" ("tail reversals"), which is incorrect and critical. the rest of the sentence is understandable but could be improved stylistically.
no major errors
summary: the phrase "magnetic reversals" is mistranslated as "kuyruksal geri dönüşlere" ("tail reversals"), which is incorrect and critical. the rest of the sentence is understandable but could be improved stylistically.
overall, no critical errors that inhibit comprehension, but some major and minor errors affect fluency and accuracy.
overall, no critical errors that inhibit comprehension, but some major and minor errors affect fluency and accuracy.
overall, no critical or major errors; minor style/clarity issues.
overall, no critical or major errors; minor style/clarity issues.
overall, the translation is accurate and understandable with a minor omission of explicit subject reference.
overall, the translation is accurate and understandable with a minor omission of explicit subject reference.
no major errors
no minor errors
no major errors
no minor errors
no major errors
no minor errors
no major errors
no minor errors
no other minor errors detected.
no other minor errors detected.
no major errors
no major errors
- style: minor awkwardness due to the phrasing "bunu, sözleşmeye göre 1500 civarında sona eren geç orta çağ izledi" but it is acceptable and understandable
- style: minor awkwardness due to the phrasing "bunu, sözleşmeye göre 1500 civarında sona eren geç orta çağ izledi" but it is acceptable and understandable
overall, no critical or major errors. minor terminology precision issue with "original score".
overall, no critical or major errors. minor terminology precision issue with "original score".
overall, the main issue is a minor to major accuracy omission and slight awkwardness in phrasing.
overall, the main issue is a minor to major accuracy omission and slight awkwardness in phrasing.
overall, the main issue is a major accuracy/mistranslation error affecting comprehension.
overall, the main issue is a major accuracy/mistranslation error affecting comprehension.
no major errors
no minor errors
no major errors
no minor errors
- major error: mistranslation of "minor burns" as "küçük yanılarla" (small mistakes).
- minor error: omission of "malfunctioning" nuance.
- minor fluency issues with punctuation and sentence structure.
- major error: mistranslation of "minor burns" as "küçük yanılarla" (small mistakes).
- minor error: omission of "malfunctioning" nuance.
- minor fluency issues with punctuation and sentence structure.
- critical error: mistranslation of what apple called "non-serious" (incidents vs. company).
- minor stylistic awkwardness.
- critical error: mistranslation of what apple called "non-serious" (incidents vs. company).
- minor stylistic awkwardness.
no critical errors.
no minor errors.
no critical errors.
no minor errors.
no critical errors.
no major errors.
no minor errors.
no critical errors.
no major errors.
no minor errors.
no other major errors
no other minor errors
no other major errors
no other minor errors
no critical errors.
no critical errors.
no major errors
no minor errors
no major errors
no minor errors
overall, the translation is accurate and understandable with only a minor stylistic awkwardness.
overall, the translation is accurate and understandable with only a minor stylistic awkwardness.
no other major errors
no other major errors
no major errors
no major errors
no other major errors
no other major errors
no minor errors identified.
no minor errors identified.
overall, this is a minor stylistic/fluency issue rather than a clear error.
overall, this is a minor stylistic/fluency issue rather than a clear error.
no major errors
no major errors
overall, the translation is accurate and fluent with no critical or major errors.
overall, the translation is accurate and fluent with no critical or major errors.
no major errors
no major errors
overall, no critical or major errors; minor style issue.
overall, no critical or major errors; minor style issue.
no major errors
no major errors
no critical errors.
no major errors.
overall, minor stylistic awkwardness.
minor: style/awkward
no critical errors.
no major errors.
overall, minor stylistic awkwardness.
minor: style/awkward
overall, the main issue is minor to major accuracy and slight awkwardness in style.
overall, the main issue is minor to major accuracy and slight awkwardness in style.
no other major errors
no other major errors
overall, no critical or major errors; minor stylistic and fluency issues only.
overall, no critical or major errors; minor stylistic and fluency issues only.
no major errors
no major errors
no other major errors
no minor errors
no other major errors
no minor errors
no major errors
no major errors
no other major errors
no minor errors
no other major errors
no minor errors
overall assessment: no critical or major errors; minor accuracy nuance regarding "formal sense."
overall assessment: no critical or major errors; minor accuracy nuance regarding "formal sense."
no major errors
no major errors
overall, the translation is accurate and fluent with only a minor grammatical number agreement issue.
overall, the translation is accurate and fluent with only a minor grammatical number agreement issue.
overall, no critical or major errors; minor punctuation issue.
overall, no critical or major errors; minor punctuation issue.
no other major errors
no other major errors
overall, the translation is accurate and fluent with no critical or major errors.
overall, the translation is accurate and fluent with no critical or major errors.
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
overall, the translation is accurate and fluent with only a minor stylistic awkwardness.
overall, the translation is accurate and fluent with only a minor stylistic awkwardness.
- major error: mistranslation of "dead pharaoh" (singular) instead of plural "dead pharaohs."
- no critical errors.
- minor or no other errors.
- major error: mistranslation of "dead pharaoh" (singular) instead of plural "dead pharaohs."
- no critical errors.
- minor or no other errors.
overall, this is a minor stylistic issue and does not hinder comprehension.
overall, this is a minor stylistic issue and does not hinder comprehension.
- fluency/grammar: the phrase "solo per se stesso e altri membri" is slightly awkward in italian; a more natural phrasing might be "solo per sé e per altri membri" (using the accented "sé" and including the preposition "per" before "altri membri"). however, this is a minor stylistic/grammar issue that does not hinder comprehension.
- fluency/grammar: the phrase "solo per se stesso e altri membri" is slightly awkward in italian; a more natural phrasing might be "solo per sé e per altri membri" (using the accented "sé" and including the preposition "per" before "altri membri"). however, this is a minor stylistic/grammar issue that does not hinder comprehension.
No error level for the translation accurately conveys the meaning of the source text with correct grammar, terminology, and style.
No error level for the translation accurately conveys the meaning of the source text with correct grammar, terminology, and style.
no major errors
no major errors
overall, the translation is accurate and fluent with only a minor stylistic awkwardness.
overall, the translation is accurate and fluent with only a minor stylistic awkwardness.
no other major errors
no other major errors
No error level for the translation is accurate, fluent, and appropriate in style and terminology.
No error level for the translation is accurate, fluent, and appropriate in style and terminology.
no critical or major errors.
no critical or major errors.
no critical or major errors.
no critical or major errors.
no major errors
no major errors
no major errors
no major errors
minor fluency/register - "la vostra" (formal/plural "your" may be inconsistent depending on context, but not a strong error)
minor fluency/register - "la vostra" (formal/plural "your" may be inconsistent depending on context, but not a strong error)
no critical or major errors.
no critical or major errors.
overall, the translation is accurate and fluent with only a minor preposition usage issue.
overall, the translation is accurate and fluent with only a minor preposition usage issue.
no major errors
no major errors
no minor errors detected
no minor errors detected
No error level for the translation is accurate, fluent, and appropriate in style and terminology.
No error level for the translation is accurate, fluent, and appropriate in style and terminology.
punctuation - missing comma after "missaggio del suono" before "e sceneggiatura originale" (oxford comma), but this is minor and stylistic.
overall, no critical or major errors; minor issues only.
punctuation - missing comma after "missaggio del suono" before "e sceneggiatura originale" (oxford comma), but this is minor and stylistic.
overall, no critical or major errors; minor issues only.
no major errors
no minor errors
no major errors
no minor errors
no major errors
no major errors
no major errors
no major errors
no major errors
no minor errors
no major errors
no minor errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no other major errors.
no other minor errors.
no other major errors.
no other minor errors.
no other major errors
no other major errors
no major errors
no major errors
no other major errors
no other minor errors
no other major errors
no other minor errors
no other major errors
no other major errors
no major errors
no major errors
no critical or major errors detected.
no critical or major errors detected.
overall, no critical or major errors; minor style/fluency issues only.
overall, no critical or major errors; minor style/fluency issues only.
no major errors
no minor errors
no major errors
no minor errors
overall, the translation is accurate and fluent with only minor stylistic issues.
overall, the translation is accurate and fluent with only minor stylistic issues.
no other major errors
no other major errors
no major errors
no major errors
overall, no critical or major errors; minor possible terminology nuance but acceptable.
no critical errors.
overall, no critical or major errors; minor possible terminology nuance but acceptable.
no critical errors.
no major errors
no major errors
no major errors
no minor errors
no major errors
no minor errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no other major errors
no other major errors
no other major errors
no other major errors
no other major errors
overall, the main issue is the mistranslation of "pig catchers" which is critical.
no other major errors
overall, the main issue is the mistranslation of "pig catchers" which is critical.
no major errors
no major errors
no major errors
no major errors
no other major errors
no other major errors
no critical errors.
no major errors.
no minor errors.
no critical errors.
no major errors.
no minor errors.
no other major errors
no other major errors
- style/awkward - the sentence inside the quotes is somewhat literal and could be smoothed for naturalness, but this is minor.
- style/awkward - the sentence inside the quotes is somewhat literal and could be smoothed for naturalness, but this is minor.
no major errors
no minor errors
no major errors
no minor errors
no major errors
no major errors
overall, the translation is accurate and fluent with only minor stylistic awkwardness.
overall, the translation is accurate and fluent with only minor stylistic awkwardness.
no major errors
no major errors
no major errors
no minor errors
no major errors
no minor errors
overall assessment: no critical errors; minor punctuation issues; no major errors.
overall assessment: no critical errors; minor punctuation issues; no major errors.
no critical errors.
no major errors.
no critical errors.
no major errors.
overall classification: no critical or major errors; minor issues related to clarity and style.
overall classification: no critical or major errors; minor issues related to clarity and style.
overall, these are very minor and do not hinder comprehension.
overall, these are very minor and do not hinder comprehension.
no other minor errors detected
no other minor errors detected
no other major errors identified
no other major errors identified
no other major errors
no other major errors
no critical errors.
overall: no critical or major errors; minor addition acceptable.
no critical errors.
minor error: accuracy/addition - "внаслідок дтп" (as a result of the accident) is an addition not explicitly in the source but acceptable.
no critical errors.
overall: no critical or major errors; minor addition acceptable.
no critical errors.
minor error: accuracy/addition - "внаслідок дтп" (as a result of the accident) is an addition not explicitly in the source but acceptable.
no major errors
no major errors
No error level for the translation accurately conveys the meaning of the source text, with correct terminology and grammar. the location names, charges, and sequence of events are properly translated. the style and register are appropriate for the context.
No error level for the translation accurately conveys the meaning of the source text, with correct terminology and grammar. the location names, charges, and sequence of events are properly translated. the style and register are appropriate for the context.
overall, the critical error is the incorrect reference of the relative clause, which inhibits comprehension.
overall, the critical error is the incorrect reference of the relative clause, which inhibits comprehension.
no major errors
no major errors
overall, the main issue is a major mistranslation of "child abuse" and slight ambiguity in pronoun reference.
overall, the main issue is a major mistranslation of "child abuse" and slight ambiguity in pronoun reference.
no other major errors
no other major errors
no major errors
no major errors
no other major errors
no other minor errors
no other major errors
no other minor errors
no other major errors
no other major errors
no major errors
no major errors
overall, the translation is accurate and understandable with minor stylistic and fluency issues.
overall, the translation is accurate and understandable with minor stylistic and fluency issues.
no major errors
no major errors
no other major errors
no minor errors
no other major errors
no minor errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
overall, the critical error is the mistranslation of plural to singular, which affects comprehension.
overall, the critical error is the mistranslation of plural to singular, which affects comprehension.
no major errors
no major errors
no major errors
no major errors
overall, the translation is accurate and fluent with only minor stylistic considerations.
overall, the translation is accurate and fluent with only minor stylistic considerations.
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
- major error: mistranslation of case for "династией" (should be plural instrumental).
- minor errors: terminology choices for dynasty names.
- major error: mistranslation of case for "династией" (should be plural instrumental).
- minor errors: terminology choices for dynasty names.
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no major errors
no minor errors
no major errors
no minor errors
no other major errors
overall, the main critical error is the mistranslation of the subject performing the action.
no other major errors
overall, the main critical error is the mistranslation of the subject performing the action.
no major errors
no major errors
no major errors
no major errors
no other major errors
- critical accuracy/mistranslation error due to incorrect subject of migration (pigs instead of disease).
no other major errors
- critical accuracy/mistranslation error due to incorrect subject of migration (pigs instead of disease).
no major errors
no major errors
- punctuation - commas around "john hancock" and "charles thomson" are correct but could be reconsidered for smoother flow; however, this is minor and acceptable.
- punctuation - commas around "john hancock" and "charles thomson" are correct but could be reconsidered for smoother flow; however, this is minor and acceptable.
no other major errors
no other major errors
overall, the translation is accurate and fluent with no critical or major errors. the minor issue is negligible.
overall, the translation is accurate and fluent with no critical or major errors. the minor issue is negligible.
overall, the main issue is the omission of "for example," which affects the nuance but does not critically hinder comprehension.
overall, the main issue is the omission of "for example," which affects the nuance but does not critically hinder comprehension.
no major errors
no minor errors
no major errors
no minor errors
no major errors
no major errors
no major errors
no major errors
no other major errors
no other major errors
no critical or major errors. the translation is accurate and understandable.
no critical or major errors. the translation is accurate and understandable.

In [19]:
gpt_results_df = pd.DataFrame(gpt_results)

gpt_results_df.to_csv(
    "../data/dataset_qe/gemba_gpt4_1_mini_qe_outputs.tsv",
    sep="\t",
    index=False
)

In [22]:
print(gpt_results_df.shape)
print(gpt_results_df["qe_gemba_gpt4_1_mini"].isna().sum())
gpt_results_df.head(10)

(5160, 4)
0

,unit_id,qe_gemba_gpt4_1_mini,gemba_gpt4_1_mini_errors,gemba_gpt4_1_mini_raw_output
0,flores101-main-tur-100-pe1-1,0,{},No errors detected. \nCategory: no-error
1,flores101-main-tur-100-pe1-2,0,{},No errors detected. The translation accurately...
2,flores101-main-tur-100-pe1-3,-12,{'major': ['accuracy/mistranslation - the turk...,Major:\naccuracy/mistranslation - The Turkish ...
3,flores101-main-tur-100-pe1-4,-7,{'major': ['accuracy/mistranslation - the turk...,Critical:\nno-error\n\nMajor:\naccuracy/mistra...
4,flores101-main-tur-100-pe1-5,-25,"{'critical': ['accuracy/mistranslation - ""bu s...","Critical:\naccuracy/mistranslation - ""bu sabır..."
5,flores101-main-tur-101-pe2-1,-25,{'critical': ['accuracy/omission - the transla...,Critical:\naccuracy/omission - The translation...
6,flores101-main-tur-101-pe2-2,0,{},No errors detected. \nCategory: no-error
7,flores101-main-tur-101-pe2-3,-9,"{'major': ['accuracy/omission - the phrase ""no...",Critical:\nno-error\n\nMajor:\naccuracy/omissi...
8,flores101-main-tur-103-pe1-1,0,{},No errors detected. The translation is accurat...
9,flores101-main-tur-103-pe1-2,-1,{'minor': ['terminology/inappropriate for cont...,Critical:\nno-error\n\nMajor:\nno-error\n\nMin...

In [23]:
# Create final QE dataframe from your existing working dataframe
qe_df = gemba_input_df.copy()

In [24]:
qe_df = qe_df.merge(
    gemma_results_df[
        [
            "unit_id",
            "qe_gemba_gemma3"
        ]
    ],
    on="unit_id",
    how="left",
    validate="one_to_one"
)

In [25]:

qe_df = qe_df.merge(
    gpt_results_df[
        [
            "unit_id",
            "qe_gemba_gpt4_1_mini"
        ]
    ],
    on="unit_id",
    how="left",
    validate="one_to_one"
)

In [30]:
"""
qe_df.to_csv(
    "../data/dataset_qe/divemt_all_qe_scores.tsv",
    sep="\t",
    index=False
)
"""
print(qe_df.shape)
qe_df.head(10)

(5160, 69)

,unit_id,flores_id,item_id,subject_id,task_type,translation_type,src_len_chr,mt_len_chr,tgt_len_chr,src_len_wrd,...,mt_annotations,tgt_tokens,tgt_annotations,src_wmt22_qe,mt_wmt22_qe,qe_cometkiwi,source_lang,target_lang,qe_gemba_gemma3,qe_gemba_gpt4_1_mini
0,flores101-main-tur-100-pe1-1,894,flores101-main-1001,tur_t1,pe1,pe,124,126.0,128,21,...,"[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['Yeniden', 'giriş', 'şoku', ',', 'kültür', 'ş...","[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'OK', 'O...",0.863117,English,Turkish,0,0
1,flores101-main-tur-100-pe1-2,895,flores101-main-1002,tur_t1,pe1,pe,137,117.0,117,22,...,"[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['Yeni', 'kültüre', 'kolayca', 'uyum', 'sağlay...","[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...",0.868266,English,Turkish,0,0
2,flores101-main-tur-100-pe1-3,896,flores101-main-1003,tur_t1,pe1,pe,127,133.0,148,22,...,"[{'lemma': 'yurtdışı', 'upos': 'NOUN', 'feats'...","['Yurtdışında', 'yaşadıktan', 'sonra', 'ülkeni...","[{'lemma': 'yurtdışı', 'upos': 'NOUN', 'feats'...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'BAD', 'B...","['OK', 'OK', 'OK', 'BAD', 'OK', 'BAD', 'OK', '...",0.891622,English,Turkish,0,-12
3,flores101-main-tur-100-pe1-4,897,flores101-main-1004,tur_t1,pe1,pe,134,145.0,166,22,...,"[{'lemma': 'ilk', 'upos': 'ADJ', 'feats': '', ...","['Yurt', 'dışına', 'ilk', 'çıktığınızda', 'çev...","[{'lemma': 'yurt', 'upos': 'NOUN', 'feats': 'C...","['OK', 'OK', 'OK', 'BAD', 'OK', 'BAD', 'BAD', ...","['BAD', 'BAD', 'BAD', 'OK', 'BAD', 'BAD', 'OK'...",0.865835,English,Turkish,-1,-7
4,flores101-main-tur-100-pe1-5,898,flores101-main-1005,tur_t1,pe1,pe,107,89.0,94,15,...,"[{'lemma': 'insan', 'upos': 'NOUN', 'feats': '...","['İnsanlar', ',', 'ülkesine', 'dönenlere', 'de...","[{'lemma': 'insan', 'upos': 'NOUN', 'feats': '...","['OK', 'BAD', 'OK', 'BAD', 'BAD', 'BAD', 'OK',...","['OK', 'BAD', 'BAD', 'BAD', 'BAD', 'OK', 'OK',...",0.635008,English,Turkish,-25,-25
5,flores101-main-tur-101-pe2-1,18,flores101-main-1011,tur_t1,pe2,pe,117,110.0,121,18,...,"[{'lemma': '1960', 'upos': 'PROPN', 'feats': '...","[""1960'larda"", 'Brzezinski', ',', 'John', 'F',...","[{'lemma': '1960', 'upos': 'ADJ', 'feats': 'Ca...","['OK', 'OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'O...","['OK', 'OK', 'OK', 'BAD', 'BAD', 'OK', 'OK', '...",0.873991,English,Turkish,-1,-25
6,flores101-main-tur-101-pe2-2,19,flores101-main-1012,tur_t1,pe2,pe,157,192.0,192,24,...,"[{'lemma': '1976', 'upos': 'NUM', 'feats': 'Ca...","['1976', 'seçimlerinde', ""Carter'a"", 'dış', 'p...","[{'lemma': '1976', 'upos': 'NUM', 'feats': 'Ca...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...",0.895587,English,Turkish,0,0
7,flores101-main-tur-101-pe2-3,20,flores101-main-1013,tur_t1,pe2,pe,275,272.0,285,42,...,"[{'lemma': 'NSA', 'upos': 'NOUN', 'feats': 'Ab...","['NSA', 'olarak', ""Carter'a"", ""1978'deki"", 'Ca...","[{'lemma': 'NSA', 'upos': 'NOUN', 'feats': 'Ab...","['OK', 'OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'O...","['OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'BAD', '...",0.870157,English,Turkish,-6,-9
8,flores101-main-tur-103-pe1-1,669,flores101-main-1031,tur_t1,pe1,pe,195,170.0,159,28,...,"[{'lemma': 'bir', 'upos': 'DET', 'feats': 'Def...","['Bir', 'kuruluş', ',', 'eğitim', 'kurumu', 'k...","[{'lemma': 'bir', 'upos': 'DET', 'feats': 'Def...","['BAD', 'OK', 'OK', 'BAD', 'BAD', 'OK', 'BAD',...","['OK', 'BAD', 'BAD', 'BAD', 'BAD', 'BAD', 'BAD...",0.899022,English,Turkish,-1,0
9,flores101-main-tur-103-pe1-2,670,flores101-main-1032,tur_t1,pe1,pe,143,141.0,136,19,...,"[{'lemma': 'bir', 'upos': 'DET', 'feats': 'Def...","['Tüm', 'mevcut', 'kaynaklar', 'bir', 'kuruluş...","[{'lemma': 'tüm', 'upos': 'DET', 'feats': '', ...","['OK', 'BAD', 'BAD', 'BAD', 'OK', 'OK', 'OK', ...","['BAD', 'BAD', 'BAD', 'BAD', 'BAD', 'BAD', 'BA...",0.882316,English,Turkish,-6,-1